/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package pbo_proyek;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.io.FileUtils;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author alan bulain
 */
public class DetailStok_Form extends javax.swing.JFrame {
    
    /**
     * Creates new form DetailStok_Form
     */
    ArrayList<String[]> listjenis;
    public DetailStok_Form() {
        initComponents();
        loadcmb();
    }
    
    public DetailStok_Form(String[] data){
        this();
        this.data_stok = data;
        loadImage(data_stok[7],1);
        tb_nama.setText(data[2]);
        tb_harga.setText(data[4]);
        tb_stok.setText(data[3]);
        lbl_kode.setText(data[1]);
        if(data[6].equals("1")){
            cb_jenis.setSelectedIndex(0);
        }else if(data[6].equals("2")){
            cb_jenis.setSelectedIndex(1);
        }else if(data[6].equals("3")){
            cb_jenis.setSelectedIndex(2);
        }else if(data[6].equals("4")){
            cb_jenis.setSelectedIndex(3);
        }else if(data[6].equals("5")){
            cb_jenis.setSelectedIndex(4);
        }else if(data[6].equals("6")){
            cb_jenis.setSelectedIndex(5);
        }else if(data[6].equals("7")){
            cb_jenis.setSelectedIndex(6);
        }
    }
    private Form_Stock frm_stc;
    private String[] data_stok;
    
    public void loadcmb(){
        listjenis = DB.query("SELECT * FROM JENIS_BARANG");
        
        for (String[] s :listjenis) {
            cb_jenis.addItem(s[1]);
        }
    }
    
    public void setFrm_stc(Form_Stock frm_stc) {
        this.frm_stc = frm_stc;
    }
    public Form_Stock getFrm_stc() {
        return frm_stc;
    }
    public String[] getData_stock() {
        return data_stok;
    }
    
    public void setData_stock(String[] data_stok) {
        this.data_stok = data_stok;
    }
    BufferedImage bi;
    File f;
    // 0 --> File select,
    // 1 --> DB,
    // -1 --> angka random. supaya keluar image not found
    public void loadImage(String fileName, int mode){
        InputStream is;
        Image img;
        ImageIcon img_icon;
        try {
            if(!fileName.equalsIgnoreCase("null") && !fileName.equals("")){
                if(mode == 0){
                    is = new FileInputStream(fileName);
                }else{
                    is = new FileInputStream(System.getProperty("user.dir")+"/Images/Barang/"+fileName);
                }
            }else{
                is = Form_Login.class.getResourceAsStream("Images/no_img.png");
            }
            bi = ImageIO.read(is);
            img = bi.getScaledInstance(lbl_img.getWidth(), -1, Image.SCALE_SMOOTH);
            img_icon = new ImageIcon(img);
            lbl_img.setIcon(img_icon);
        }catch (FileNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Image not found","Error",JOptionPane.ERROR_MESSAGE);
            f = null;
            loadImage("null",0);
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Bad file format","Error",JOptionPane.ERROR_MESSAGE);
            f = null;
            loadImage("null",0);
        }
    }
    public static boolean isNumeric(String str) {
        try {
            Double.parseDouble(str);
            return true;
        } catch(NumberFormatException e){
            return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_kode = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tb_harga = new javax.swing.JTextField();
        cb_jenis = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        tb_stok = new javax.swing.JTextField();
        btn_updatestok = new javax.swing.JButton();
        btn_deletestok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_nama = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btn_changepicture = new javax.swing.JButton();
        lbl_img = new javax.swing.JLabel();
        btn_removepicture = new javax.swing.JButton();
        pl_titlebar = new javax.swing.JPanel();
        lbl_close = new javax.swing.JLabel();
        lbl_minimize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(470, 412));
        setUndecorated(true);

        pl.setBackground(new java.awt.Color(58, 58, 58));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(222, 222, 222));
        jLabel1.setText("Kode :");

        lbl_kode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_kode.setForeground(new java.awt.Color(222, 222, 222));
        lbl_kode.setText("D<XXXX0001>");

        jLabel4.setForeground(new java.awt.Color(222, 222, 222));
        jLabel4.setText("Nama Barang :");

        jLabel7.setForeground(new java.awt.Color(222, 222, 222));
        jLabel7.setText("Stok :");

        jLabel8.setForeground(new java.awt.Color(222, 222, 222));
        jLabel8.setText("Harga :");

        tb_harga.setBackground(new java.awt.Color(244, 244, 244));
        tb_harga.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_harga.setForeground(new java.awt.Color(58, 58, 58));
        tb_harga.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_harga.setCaretColor(new java.awt.Color(58, 58, 58));
        tb_harga.setMaximumSize(new java.awt.Dimension(6, 22));

        cb_jenis.setBackground(new java.awt.Color(244, 244, 244));
        cb_jenis.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cb_jenis.setForeground(new java.awt.Color(58, 58, 58));
        cb_jenis.setOpaque(false);

        jLabel9.setForeground(new java.awt.Color(222, 222, 222));
        jLabel9.setText("Jenis :");

        tb_stok.setBackground(new java.awt.Color(244, 244, 244));
        tb_stok.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_stok.setForeground(new java.awt.Color(58, 58, 58));
        tb_stok.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_stok.setCaretColor(new java.awt.Color(58, 58, 58));
        tb_stok.setMaximumSize(new java.awt.Dimension(6, 22));

        btn_updatestok.setBackground(new java.awt.Color(222, 222, 222));
        btn_updatestok.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        btn_updatestok.setForeground(new java.awt.Color(58, 58, 58));
        btn_updatestok.setText(" Update");
        btn_updatestok.setBorder(null);
        btn_updatestok.setContentAreaFilled(false);
        btn_updatestok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_updatestok.setFocusPainted(false);
        btn_updatestok.setOpaque(true);
        btn_updatestok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updatestokActionPerformed(evt);
            }
        });

        btn_deletestok.setBackground(new java.awt.Color(222, 222, 222));
        btn_deletestok.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        btn_deletestok.setForeground(new java.awt.Color(58, 58, 58));
        btn_deletestok.setText("Delete");
        btn_deletestok.setBorder(null);
        btn_deletestok.setContentAreaFilled(false);
        btn_deletestok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_deletestok.setFocusPainted(false);
        btn_deletestok.setOpaque(true);
        btn_deletestok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletestokActionPerformed(evt);
            }
        });

        tb_nama.setBackground(new java.awt.Color(244, 244, 244));
        tb_nama.setColumns(20);
        tb_nama.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_nama.setForeground(new java.awt.Color(58, 58, 58));
        tb_nama.setRows(5);
        tb_nama.setCaretColor(new java.awt.Color(58, 58, 58));
        jScrollPane1.setViewportView(tb_nama);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(222, 222, 222));
        jLabel2.setText("DETAIL STOK");

        btn_changepicture.setBackground(new java.awt.Color(222, 222, 222));
        btn_changepicture.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_changepicture.setForeground(new java.awt.Color(58, 58, 58));
        btn_changepicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_proyek/Images/wrench-solid.png"))); // NOI18N
        btn_changepicture.setText("Change Picture");
        btn_changepicture.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1));
        btn_changepicture.setContentAreaFilled(false);
        btn_changepicture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_changepicture.setFocusPainted(false);
        btn_changepicture.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_changepicture.setIconTextGap(10);
        btn_changepicture.setOpaque(true);
        btn_changepicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changepictureActionPerformed(evt);
            }
        });

        lbl_img.setBackground(new java.awt.Color(222, 222, 222));
        lbl_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_img.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_img.setIconTextGap(0);

        btn_removepicture.setBackground(new java.awt.Color(222, 222, 222));
        btn_removepicture.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_removepicture.setForeground(new java.awt.Color(58, 58, 58));
        btn_removepicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_proyek/Images/trash-solid.png"))); // NOI18N
        btn_removepicture.setText("Remove Picture");
        btn_removepicture.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1));
        btn_removepicture.setContentAreaFilled(false);
        btn_removepicture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_removepicture.setFocusPainted(false);
        btn_removepicture.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_removepicture.setIconTextGap(10);
        btn_removepicture.setOpaque(true);
        btn_removepicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removepictureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plLayout = new javax.swing.GroupLayout(pl);
        pl.setLayout(plLayout);
        plLayout.setHorizontalGroup(
            plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(plLayout.createSequentialGroup()
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_removepicture, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_kode)
                                .addComponent(lbl_img, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_changepicture, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)
                            .addComponent(cb_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(tb_stok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tb_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(plLayout.createSequentialGroup()
                                .addComponent(btn_updatestok, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_deletestok, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        plLayout.setVerticalGroup(
            plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plLayout.createSequentialGroup()
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(plLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_kode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plLayout.createSequentialGroup()
                        .addComponent(cb_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8))
                    .addGroup(plLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lbl_img, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_removepicture, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_changepicture, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_updatestok, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deletestok, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127))
        );

        pl_titlebar.setBackground(new java.awt.Color(58, 58, 58));
        pl_titlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pl_titlebarMouseDragged(evt);
            }
        });
        pl_titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pl_titlebarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pl_titlebarMousePressed(evt);
            }
        });

        lbl_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_proyek/Images/times-solid.png"))); // NOI18N
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
        });

        lbl_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_proyek/Images/window-minimize-solid.png"))); // NOI18N
        lbl_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_minimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pl_titlebarLayout = new javax.swing.GroupLayout(pl_titlebar);
        pl_titlebar.setLayout(pl_titlebarLayout);
        pl_titlebarLayout.setHorizontalGroup(
            pl_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_titlebarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_minimize)
                .addGap(18, 18, 18)
                .addComponent(lbl_close)
                .addContainerGap())
        );
        pl_titlebarLayout.setVerticalGroup(
            pl_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pl_titlebarLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(lbl_close))
            .addComponent(lbl_minimize)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pl_titlebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pl_titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pl, javax.swing.GroupLayout.PREFERRED_SIZE, 386, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public boolean checkAngka(String t){
        try {
            int a = Integer.parseInt(t);
        } catch (Exception e) {
            return false;
        }
        return true;
    }
    
    private void btn_updatestokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updatestokActionPerformed
        // TODO add your handling code here:
        boolean valid =true;
        String nama = tb_nama.getText();
        int jenis = cb_jenis.getSelectedIndex();
        String hrg = tb_harga.getText();
        String stok = tb_stok.getText();
        String img_name = data_stok[7];
        if(tb_nama.getText().isEmpty()){
            valid =false;
            JOptionPane.showMessageDialog(null, "Nama barang tidak boleh kosong","Error",JOptionPane.INFORMATION_MESSAGE);
        }
        if(tb_harga.getText().isEmpty()){
            valid =false;
            JOptionPane.showMessageDialog(null, "Harga barang tidak boleh kosong","Error",JOptionPane.INFORMATION_MESSAGE);
        }else{
            if(!checkAngka(tb_harga.getText())){
                valid =false;
                JOptionPane.showMessageDialog(null, "Harga barang harus berupa angka","Error",JOptionPane.ERROR_MESSAGE);
            }else{
                int harga = Integer.parseInt(tb_harga.getText());
                if (harga < 1){
                    valid =false;
                    JOptionPane.showMessageDialog(null, "Harga Barang tidak boleh kurang dari 1!","Error",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        if(tb_stok.getText().isEmpty()){
            valid =false;
            JOptionPane.showMessageDialog(null, "Stok barang tidak boleh kosong","Error",JOptionPane.INFORMATION_MESSAGE);
        }else{
            if(!checkAngka(tb_stok.getText())){
                valid =false;
                JOptionPane.showMessageDialog(null, "Stok barang harus berupa angka","Error",JOptionPane.ERROR_MESSAGE);
            }else{
                int stck = Integer.parseInt(tb_stok.getText());
                if (stck < 0){
                    valid =false;
                    JOptionPane.showMessageDialog(null, "Stok Barang tidak boleh kurang dari 0!","Error",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        if(f != null){
            img_name = data_stok[1] + "." + FilenameUtils.getExtension(f.getName());
        }else{
            img_name = "NULL";
        }
        if(valid){
            int output = DB.update("UPDATE barang SET nama = ?, stok = ?, harga = ?,fk_jenis_barang = ?,images = ?  WHERE id = ?",
                    new Object[] {nama,stok,hrg,jenis+1,img_name,data_stok[0]});
            try {
                if(f != null){
                    File f_copy = new File(System.getProperty("user.dir")+"/Images/Barang/"+img_name);
                    FileUtils.copyFile(f, f_copy);
                }
            } catch (Exception e) {
            }
            
            if(output != 0){
                frm_stc.loadDgv();
                frm_stc.search();
                frm_stc.setIdx(-1);
                JOptionPane.showMessageDialog(null, "Sukses ubah data","Sukses",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_updatestokActionPerformed

    private void btn_deletestokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletestokActionPerformed
        // TODO add your handling code here:
        
        if(JOptionPane.showConfirmDialog(null, "Yakin hapus barang "+data_stok[2]+" ?","Hapus barang",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            int output = DB.delete("UPDATE barang SET STATUS = 0 WHERE id = ?",new Object[] {data_stok[0]});
            if(output <= 0){
                JOptionPane.showMessageDialog(null, "Error saat menghapus!","Error",JOptionPane.ERROR_MESSAGE);
            }else{
                frm_stc.loadDgv();
                frm_stc.search();
                frm_stc.setIdx(-1);
                JOptionPane.showMessageDialog(null, "Sukses delete barang","Sukses",JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btn_deletestokActionPerformed

    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lbl_closeMouseClicked

    private void lbl_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizeMouseClicked
        // TODO add your handling code here:
        setState(this.ICONIFIED);
    }//GEN-LAST:event_lbl_minimizeMouseClicked
    
    int state_mode = -1; //-1 not full, 1 full screen
    private int x,y;
    
    private void pl_titlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pl_titlebarMouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_pl_titlebarMouseDragged

    private void pl_titlebarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pl_titlebarMouseClicked

    }//GEN-LAST:event_pl_titlebarMouseClicked

    private void pl_titlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pl_titlebarMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pl_titlebarMousePressed

    private void btn_removepictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removepictureActionPerformed
        // TODO add your handling code here:
        f = null;
        loadImage("", -1);
    }//GEN-LAST:event_btn_removepictureActionPerformed

    private void btn_changepictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changepictureActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images", "jpg", "jpeg", "png", "bmp");
        fc.setFileFilter(filter);
        int result = fc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            f = fc.getSelectedFile();
            loadImage(f.getPath(),0);
        }
    }//GEN-LAST:event_btn_changepictureActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailStok_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailStok_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailStok_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailStok_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailStok_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_changepicture;
    private javax.swing.JButton btn_deletestok;
    private javax.swing.JButton btn_removepicture;
    private javax.swing.JButton btn_updatestok;
    private javax.swing.JComboBox<String> cb_jenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JLabel lbl_kode;
    private javax.swing.JLabel lbl_minimize;
    private javax.swing.JPanel pl;
    private javax.swing.JPanel pl_titlebar;
    private javax.swing.JTextField tb_harga;
    private javax.swing.JTextArea tb_nama;
    private javax.swing.JTextField tb_stok;
    // End of variables declaration//GEN-END:variables
}
