/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbo_proyek;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author alan bulain
 */
public class DetailStok_Form extends javax.swing.JFrame {

    /**
     * Creates new form DetailStok_Form
     */
    ArrayList<String[]> listjenis;
    public DetailStok_Form() {
        initComponents();
        loadcmb();
    }
    public DetailStok_Form(String[] data){
        this();
        this.data_stok = data;
        tb_nama.setText(data[2]);
        tb_harga.setText(data[4]);
        tb_stok.setText(data[3]);
        lbl_kode.setText(data[1]);
        if(data[6].equals("1")){
            cb_jenis.setSelectedIndex(0);
        }else if(data[6].equals("2")){
            cb_jenis.setSelectedIndex(1);
        }else if(data[6].equals("3")){
            cb_jenis.setSelectedIndex(2);
        }else if(data[6].equals("4")){
            cb_jenis.setSelectedIndex(3);
        }else if(data[6].equals("5")){
            cb_jenis.setSelectedIndex(4);
        }else if(data[6].equals("6")){
            cb_jenis.setSelectedIndex(5);
        }else if(data[6].equals("7")){
            cb_jenis.setSelectedIndex(6);
        }
    }
    private Form_Stock frm_stc;
    private String[] data_stok;
    public void loadcmb(){
        listjenis = DB.query("SELECT * FROM JENIS_BARANG");
        
        for (String[] s :listjenis) {
            cb_jenis.addItem(s[1]);
        }
    }
    public void setFrm_stc(Form_Stock frm_stc) {
        this.frm_stc = frm_stc;
    }
    public Form_Stock getFrm_stc() {
        return frm_stc;
    }
     public String[] getData_stock() {
        return data_stok;
    }
    
    public void setData_stock(String[] data_stok) {
        this.data_stok = data_stok;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_kode = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tb_nama = new javax.swing.JTextField();
        tb_harga = new javax.swing.JTextField();
        cb_jenis = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        tb_stok = new javax.swing.JTextField();
        btn_updatestok = new javax.swing.JButton();
        btn_deletestok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pl.setBackground(new java.awt.Color(58, 58, 58));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Kode :");

        lbl_kode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_kode.setText("D<XXXX0001>");

        jLabel4.setText("Nama :");

        jLabel7.setText("Stok :");

        jLabel8.setText("Harga :");

        tb_nama.setBackground(new java.awt.Color(244, 244, 244));
        tb_nama.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_nama.setForeground(new java.awt.Color(58, 58, 58));
        tb_nama.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_nama.setCaretColor(new java.awt.Color(58, 58, 58));

        tb_harga.setBackground(new java.awt.Color(244, 244, 244));
        tb_harga.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_harga.setForeground(new java.awt.Color(58, 58, 58));
        tb_harga.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_harga.setCaretColor(new java.awt.Color(58, 58, 58));

        cb_jenis.setBackground(new java.awt.Color(244, 244, 244));
        cb_jenis.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cb_jenis.setForeground(new java.awt.Color(58, 58, 58));
        cb_jenis.setOpaque(false);

        jLabel9.setText("Jenis :");

        tb_stok.setBackground(new java.awt.Color(244, 244, 244));
        tb_stok.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_stok.setForeground(new java.awt.Color(58, 58, 58));
        tb_stok.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_stok.setCaretColor(new java.awt.Color(58, 58, 58));

        btn_updatestok.setBackground(new java.awt.Color(222, 222, 222));
        btn_updatestok.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        btn_updatestok.setForeground(new java.awt.Color(58, 58, 58));
        btn_updatestok.setText(" Update");
        btn_updatestok.setBorder(null);
        btn_updatestok.setContentAreaFilled(false);
        btn_updatestok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_updatestok.setFocusPainted(false);
        btn_updatestok.setOpaque(true);
        btn_updatestok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updatestokActionPerformed(evt);
            }
        });

        btn_deletestok.setBackground(new java.awt.Color(222, 222, 222));
        btn_deletestok.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        btn_deletestok.setForeground(new java.awt.Color(58, 58, 58));
        btn_deletestok.setText("Delete");
        btn_deletestok.setBorder(null);
        btn_deletestok.setContentAreaFilled(false);
        btn_deletestok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_deletestok.setFocusPainted(false);
        btn_deletestok.setOpaque(true);
        btn_deletestok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletestokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plLayout = new javax.swing.GroupLayout(pl);
        pl.setLayout(plLayout);
        plLayout.setHorizontalGroup(
            plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plLayout.createSequentialGroup()
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_kode)
                            .addComponent(jLabel1)))
                    .addGroup(plLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(btn_updatestok, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addComponent(btn_deletestok, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(tb_nama)
                            .addComponent(cb_jenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tb_harga)
                            .addComponent(tb_stok))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        plLayout.setVerticalGroup(
            plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_kode)
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tb_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tb_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tb_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(plLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_deletestok, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_updatestok, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updatestokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updatestokActionPerformed
        // TODO add your handling code here:
        String nama = tb_nama.getText();
        int jenis = cb_jenis.getSelectedIndex();
        String hrg = tb_harga.getText();
        String stok = tb_stok.getText();
        int output = DB.update("UPDATE barang SET nama = ?, stok = ?, harga = ?,fk_jenis_barang = ?  WHERE id = ?", new Object[] {nama,stok,hrg,jenis+1,data_stok[0]});
        if(output != 0){
            frm_stc.loadDgv();
            frm_stc.search();
            JOptionPane.showMessageDialog(null, "Sukses ubah data","Sukses",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_updatestokActionPerformed

    private void btn_deletestokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletestokActionPerformed
        // TODO add your handling code here:

        if(JOptionPane.showConfirmDialog(null, "Yakin hapus stok "+data_stok[2]+" ?","Hapus stok",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            int output = DB.delete("UPDATE barang SET STATUS = 0 WHERE id = ?",new Object[] {data_stok[0]});
            if(output <= 0){
                JOptionPane.showMessageDialog(null, "Error saat menghapus!","Error",JOptionPane.ERROR_MESSAGE);
            }else{
                frm_stc.loadDgv();
                frm_stc.search();
                JOptionPane.showMessageDialog(null, "Sukses delete Stok","Sukses",JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btn_deletestokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailStok_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailStok_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailStok_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailStok_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailStok_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_deletestok;
    private javax.swing.JButton btn_updatestok;
    private javax.swing.JComboBox<String> cb_jenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_kode;
    private javax.swing.JPanel pl;
    private javax.swing.JTextField tb_harga;
    private javax.swing.JTextField tb_nama;
    private javax.swing.JTextField tb_stok;
    // End of variables declaration//GEN-END:variables
}
