/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package pbo_proyek;

import java.awt.Color;
import java.awt.Dimension;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author chris
 */
public class DetailAccount_Form extends javax.swing.JFrame {
    
    /**
     * Creates new form DetailAccount_Form
     */
    
    ButtonGroup btng1;
    
    public DetailAccount_Form() {
        initComponents();
        btng1 = new ButtonGroup();
        btng1.add(rb_laki);
        btng1.add(rb_perempuan);
    }
    
    public DetailAccount_Form(String[] data){
        this();
        this.data_user = data;
        tb_username.setText(data[2]);
        tb_alamat.setText(data[7]);
        tb_password.setText(data[3]);
        tb_nama.setText(data[4]);
        tb_kota.setText(data[8]);
        tb_notelp.setText(data[5]);
        if(data[6].equalsIgnoreCase("l")){
            rb_laki.setSelected(true);
        }else{
            rb_perempuan.setSelected(true);
        }
        cb_jabatan.setSelectedIndex(Integer.valueOf(data[11])-1);
        Date dt = null;
        try {
            dt = new SimpleDateFormat("yyyy-MM-dd").parse(data[7]);
        } catch (ParseException ex) {
        }
        dt_tgl.setDate(dt);
        lbl_kode.setText(data[1]);
    }
    
    private Form_Account frm_acc;
    private String[] data_user;
    private User user_login;
    
    public User getUser_login() {
        return user_login;
    }
    
    public void setUser_login(User user_login) {
        this.user_login = user_login;
    }
    
    public Form_Account getFrm_acc() {
        return frm_acc;
    }
    
    public void setFrm_acc(Form_Account frm_acc) {
        this.frm_acc = frm_acc;
    }
    
    public String[] getData_user() {
        return data_user;
    }
    
    public void setData_user(String[] data_user) {
        this.data_user = data_user;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_kode = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tb_nama = new javax.swing.JTextField();
        tb_username = new javax.swing.JTextField();
        tb_password = new javax.swing.JPasswordField();
        rb_laki = new javax.swing.JRadioButton();
        rb_perempuan = new javax.swing.JRadioButton();
        dt_tgl = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_alamat = new javax.swing.JTextArea();
        cb_jabatan = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btn_deleteuser = new javax.swing.JButton();
        btn_updateuser = new javax.swing.JButton();
        pl_titlebar = new javax.swing.JPanel();
        lbl_close = new javax.swing.JLabel();
        lbl_minimize = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tb_notelp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tb_kota = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(388, 659));
        setMinimumSize(new java.awt.Dimension(388, 659));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pl.setBackground(new java.awt.Color(58, 58, 58));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(222, 222, 222));
        jLabel1.setText("Kode :");

        lbl_kode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_kode.setForeground(new java.awt.Color(222, 222, 222));
        lbl_kode.setText("D<XXXX0001>");

        jLabel3.setForeground(new java.awt.Color(222, 222, 222));
        jLabel3.setText("Jenis Kelamin :");

        jLabel4.setForeground(new java.awt.Color(222, 222, 222));
        jLabel4.setText("Nama :");

        jLabel5.setForeground(new java.awt.Color(222, 222, 222));
        jLabel5.setText("Alamat :");

        jLabel6.setForeground(new java.awt.Color(222, 222, 222));
        jLabel6.setText("Tanggal Lahir :");

        jLabel7.setForeground(new java.awt.Color(222, 222, 222));
        jLabel7.setText("Username :");

        jLabel8.setForeground(new java.awt.Color(222, 222, 222));
        jLabel8.setText("Password :");

        tb_nama.setBackground(new java.awt.Color(244, 244, 244));
        tb_nama.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_nama.setForeground(new java.awt.Color(58, 58, 58));
        tb_nama.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_nama.setCaretColor(new java.awt.Color(58, 58, 58));
        tb_nama.setMaximumSize(new java.awt.Dimension(6, 22));

        tb_username.setBackground(new java.awt.Color(244, 244, 244));
        tb_username.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_username.setForeground(new java.awt.Color(58, 58, 58));
        tb_username.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_username.setCaretColor(new java.awt.Color(58, 58, 58));
        tb_username.setMaximumSize(new java.awt.Dimension(6, 22));

        tb_password.setBackground(new java.awt.Color(244, 244, 244));
        tb_password.setForeground(new java.awt.Color(58, 58, 58));
        tb_password.setText("Password");

        rb_laki.setBackground(new java.awt.Color(58, 58, 58));
        rb_laki.setForeground(new java.awt.Color(222, 222, 222));
        rb_laki.setText("Laki - Laki");

        rb_perempuan.setBackground(new java.awt.Color(58, 58, 58));
        rb_perempuan.setForeground(new java.awt.Color(222, 222, 222));
        rb_perempuan.setText("Perempuan");

        dt_tgl.setBackground(new java.awt.Color(222, 222, 222));
        dt_tgl.setForeground(new java.awt.Color(222, 222, 222));

        tb_alamat.setBackground(new java.awt.Color(244, 244, 244));
        tb_alamat.setColumns(20);
        tb_alamat.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_alamat.setForeground(new java.awt.Color(58, 58, 58));
        tb_alamat.setRows(5);
        tb_alamat.setCaretColor(new java.awt.Color(58, 58, 58));
        jScrollPane1.setViewportView(tb_alamat);

        cb_jabatan.setBackground(new java.awt.Color(244, 244, 244));
        cb_jabatan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cb_jabatan.setForeground(new java.awt.Color(58, 58, 58));
        cb_jabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Kasir", "Marketing" }));
        cb_jabatan.setBorder(null);
        cb_jabatan.setOpaque(false);

        jLabel9.setForeground(new java.awt.Color(222, 222, 222));
        jLabel9.setText("Jabatan :");

        btn_deleteuser.setBackground(new java.awt.Color(222, 222, 222));
        btn_deleteuser.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        btn_deleteuser.setForeground(new java.awt.Color(58, 58, 58));
        btn_deleteuser.setText("Delete");
        btn_deleteuser.setBorder(null);
        btn_deleteuser.setContentAreaFilled(false);
        btn_deleteuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_deleteuser.setFocusPainted(false);
        btn_deleteuser.setOpaque(true);
        btn_deleteuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteuserActionPerformed(evt);
            }
        });

        btn_updateuser.setBackground(new java.awt.Color(222, 222, 222));
        btn_updateuser.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        btn_updateuser.setForeground(new java.awt.Color(58, 58, 58));
        btn_updateuser.setText(" Update");
        btn_updateuser.setBorder(null);
        btn_updateuser.setContentAreaFilled(false);
        btn_updateuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_updateuser.setFocusPainted(false);
        btn_updateuser.setOpaque(true);
        btn_updateuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateuserActionPerformed(evt);
            }
        });

        pl_titlebar.setBackground(new java.awt.Color(58, 58, 58));
        pl_titlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pl_titlebarMouseDragged(evt);
            }
        });
        pl_titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pl_titlebarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pl_titlebarMousePressed(evt);
            }
        });

        lbl_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_proyek/Images/times-solid.png"))); // NOI18N
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
        });

        lbl_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_proyek/Images/window-minimize-solid.png"))); // NOI18N
        lbl_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_minimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pl_titlebarLayout = new javax.swing.GroupLayout(pl_titlebar);
        pl_titlebar.setLayout(pl_titlebarLayout);
        pl_titlebarLayout.setHorizontalGroup(
            pl_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_titlebarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_minimize)
                .addGap(18, 18, 18)
                .addComponent(lbl_close)
                .addContainerGap())
        );
        pl_titlebarLayout.setVerticalGroup(
            pl_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pl_titlebarLayout.createSequentialGroup()
                .addGroup(pl_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pl_titlebarLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl_close))
                    .addComponent(lbl_minimize))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(222, 222, 222));
        jLabel2.setText("DETAIL ACCOUNT");

        jLabel10.setForeground(new java.awt.Color(222, 222, 222));
        jLabel10.setText("No Telepon :");

        tb_notelp.setBackground(new java.awt.Color(244, 244, 244));
        tb_notelp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_notelp.setForeground(new java.awt.Color(58, 58, 58));
        tb_notelp.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_notelp.setCaretColor(new java.awt.Color(58, 58, 58));
        tb_notelp.setMaximumSize(new java.awt.Dimension(6, 22));

        jLabel11.setForeground(new java.awt.Color(222, 222, 222));
        jLabel11.setText("Kota :");

        tb_kota.setBackground(new java.awt.Color(244, 244, 244));
        tb_kota.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_kota.setForeground(new java.awt.Color(58, 58, 58));
        tb_kota.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_kota.setCaretColor(new java.awt.Color(58, 58, 58));
        tb_kota.setMaximumSize(new java.awt.Dimension(6, 22));

        javax.swing.GroupLayout plLayout = new javax.swing.GroupLayout(pl);
        pl.setLayout(plLayout);
        plLayout.setHorizontalGroup(
            plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pl_titlebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(plLayout.createSequentialGroup()
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_kode)
                            .addGroup(plLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))))
                    .addGroup(plLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(tb_notelp, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(plLayout.createSequentialGroup()
                                .addComponent(rb_laki)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_perempuan))
                            .addGroup(plLayout.createSequentialGroup()
                                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(tb_username, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(tb_nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addComponent(cb_jabatan, 0, 170, Short.MAX_VALUE)
                                    .addComponent(jLabel9)
                                    .addComponent(tb_password)))
                            .addComponent(jLabel5)
                            .addComponent(dt_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(tb_kota, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(plLayout.createSequentialGroup()
                                .addComponent(btn_updateuser, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_deleteuser, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1))
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );
        plLayout.setVerticalGroup(
            plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plLayout.createSequentialGroup()
                .addComponent(pl_titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_kode)
                .addGap(14, 14, 14)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(plLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_laki)
                            .addComponent(rb_perempuan))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tb_notelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tb_kota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dt_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_updateuser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deleteuser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void btn_updateuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateuserActionPerformed
        // TODO add your handling code here:
        String pw = String.valueOf(tb_password.getPassword());
        String gndr = "L";
        if(rb_perempuan.isSelected()){
            gndr = "P";
        }
        String dt = new SimpleDateFormat("yyyy-MM-dd").format(dt_tgl.getDate());
        int output = DB.update("UPDATE Karyawan SET username = ?, password = ?, nama = ?, nomor_telepon = ?, gender = ?, tanggal_lahir = ?, alamat = ?, kota = ?, fk_jabatan = ? WHERE id = ?", new Object[] {tb_username.getText(),pw,tb_nama.getText(),tb_notelp.getText() ,gndr,dt,tb_alamat.getText(),tb_kota.getText(),cb_jabatan.getSelectedIndex()+1,data_user[0]});
        if(output != 0){
            frm_acc.loadDgv();
            frm_acc.search();
            frm_acc.setIdx(-1);
            JOptionPane.showMessageDialog(null, "Sukses ubah data","Sukses",JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_updateuserActionPerformed

    private void btn_deleteuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteuserActionPerformed
        // TODO add your handling code here:
        if(lbl_kode.getText().equalsIgnoreCase(User.getUser_login().getKode())){
            JOptionPane.showMessageDialog(null, "Tidak bisa menghapus user yang sedang login!","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            if(JOptionPane.showConfirmDialog(null, "Yakin hapus user "+data_user[2]+" ?","Hapus User",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                int output = DB.delete("UPDATE karyawan SET STATUS = 0 WHERE id = ?",new Object[] {data_user[0]});
                if(output <= 0){
                    JOptionPane.showMessageDialog(null, "Error saat menghapus!","Error",JOptionPane.ERROR_MESSAGE);
                }else{
                    frm_acc.loadDgv();
                    frm_acc.search();
                    frm_acc.setIdx(-1);
                    JOptionPane.showMessageDialog(null, "Sukses delete user","Sukses",JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_btn_deleteuserActionPerformed

    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lbl_closeMouseClicked
    
    int state_mode = -1; //-1 not full, 1 full screen
    private int x,y;
    
    private void lbl_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizeMouseClicked
        // TODO add your handling code here:
        setState(this.ICONIFIED);
    }//GEN-LAST:event_lbl_minimizeMouseClicked
    private void pl_titlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pl_titlebarMouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);

    }//GEN-LAST:event_pl_titlebarMouseDragged

    private void pl_titlebarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pl_titlebarMouseClicked
    }//GEN-LAST:event_pl_titlebarMouseClicked

    private void pl_titlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pl_titlebarMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pl_titlebarMousePressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailAccount_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailAccount_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailAccount_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailAccount_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailAccount_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_deleteuser;
    private javax.swing.JButton btn_updateuser;
    private javax.swing.JComboBox<String> cb_jabatan;
    private com.toedter.calendar.JDateChooser dt_tgl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_kode;
    private javax.swing.JLabel lbl_minimize;
    private javax.swing.JPanel pl;
    private javax.swing.JPanel pl_titlebar;
    private javax.swing.JRadioButton rb_laki;
    private javax.swing.JRadioButton rb_perempuan;
    private javax.swing.JTextArea tb_alamat;
    private javax.swing.JTextField tb_kota;
    private javax.swing.JTextField tb_nama;
    private javax.swing.JTextField tb_notelp;
    private javax.swing.JPasswordField tb_password;
    private javax.swing.JTextField tb_username;
    // End of variables declaration//GEN-END:variables
}
