/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package pbo_proyek;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.io.FileUtils;
import org.apache.commons.io.FilenameUtils;
import static pbo_proyek.DetailStok_Form.isNumeric;

/**
 *
 * @author chris
 */
public class DetailAccount_Form extends javax.swing.JFrame {
    
    /**
     * Creates new form DetailAccount_Form
     */
    
    ButtonGroup btng1;
    
    public DetailAccount_Form() {
        initComponents();
        btng1 = new ButtonGroup();
        btng1.add(rb_laki);
        btng1.add(rb_perempuan);
        f = null;
    }
    
    public DetailAccount_Form(String[] data){
        this();
        this.data_user = data;
        loadImage(data_user[13],1);
        tb_username.setText(data[2]);
        tb_alamat.setText(data[9]);
        tb_password.setText(data[3]);
        tb_nama.setText(data[4]);
        tb_kota.setText(data[8]);
        tb_notelp.setText(data[5]);
        tb_email.setText(data[12]);
        if(data[6].equalsIgnoreCase("l")){
            rb_laki.setSelected(true);
        }else{
            rb_perempuan.setSelected(true);
        }
        cb_jabatan.setSelectedIndex(Integer.valueOf(data[11])-1);
        Date dt = null;
        try {
            dt = new SimpleDateFormat("yyyy-MM-dd").parse(data[7]);
        } catch (ParseException ex) {
        }
        dt_tgl.setDate(dt);
        lbl_kode.setText(data[1]);
    }
    
    private Form_Account frm_acc;
    private String[] data_user;
    private User user_login;
    
    public User getUser_login() {
        return user_login;
    }
    
    public void setUser_login(User user_login) {
        this.user_login = user_login;
    }
    
    public Form_Account getFrm_acc() {
        return frm_acc;
    }
    
    public void setFrm_acc(Form_Account frm_acc) {
        this.frm_acc = frm_acc;
    }
    
    public String[] getData_user() {
        return data_user;
    }
    
    public void setData_user(String[] data_user) {
        this.data_user = data_user;
    }
    
    public static boolean isNumeric(String str) {
        try {
            Double.parseDouble(str);
            return true;
        } catch(NumberFormatException e){
            return false;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_kode = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tb_nama = new javax.swing.JTextField();
        tb_username = new javax.swing.JTextField();
        tb_password = new javax.swing.JPasswordField();
        rb_laki = new javax.swing.JRadioButton();
        rb_perempuan = new javax.swing.JRadioButton();
        dt_tgl = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_alamat = new javax.swing.JTextArea();
        cb_jabatan = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btn_deleteuser = new javax.swing.JButton();
        btn_updateuser = new javax.swing.JButton();
        pl_titlebar = new javax.swing.JPanel();
        lbl_close = new javax.swing.JLabel();
        lbl_minimize = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tb_notelp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tb_kota = new javax.swing.JTextField();
        tb_email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_changepicture = new javax.swing.JButton();
        lbl_img = new javax.swing.JLabel();
        btn_removepicture = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 515));
        setMinimumSize(new java.awt.Dimension(500, 515));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pl.setBackground(new java.awt.Color(58, 58, 58));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(222, 222, 222));
        jLabel1.setText("Kode :");

        lbl_kode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_kode.setForeground(new java.awt.Color(222, 222, 222));
        lbl_kode.setText("D<XXXX0001>");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(222, 222, 222));
        jLabel3.setText("Jenis Kelamin :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(222, 222, 222));
        jLabel4.setText("Nama :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(222, 222, 222));
        jLabel5.setText("Alamat :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(222, 222, 222));
        jLabel6.setText("Tanggal Lahir :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(222, 222, 222));
        jLabel7.setText("Username :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(222, 222, 222));
        jLabel8.setText("Password :");

        tb_nama.setBackground(new java.awt.Color(244, 244, 244));
        tb_nama.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_nama.setForeground(new java.awt.Color(58, 58, 58));
        tb_nama.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_nama.setCaretColor(new java.awt.Color(58, 58, 58));
        tb_nama.setMaximumSize(new java.awt.Dimension(6, 22));

        tb_username.setBackground(new java.awt.Color(244, 244, 244));
        tb_username.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_username.setForeground(new java.awt.Color(58, 58, 58));
        tb_username.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_username.setCaretColor(new java.awt.Color(58, 58, 58));
        tb_username.setMaximumSize(new java.awt.Dimension(6, 22));

        tb_password.setBackground(new java.awt.Color(244, 244, 244));
        tb_password.setForeground(new java.awt.Color(58, 58, 58));
        tb_password.setText("Password");

        rb_laki.setBackground(new java.awt.Color(58, 58, 58));
        rb_laki.setForeground(new java.awt.Color(222, 222, 222));
        rb_laki.setText("Laki - Laki");

        rb_perempuan.setBackground(new java.awt.Color(58, 58, 58));
        rb_perempuan.setForeground(new java.awt.Color(222, 222, 222));
        rb_perempuan.setText("Perempuan");

        dt_tgl.setBackground(new java.awt.Color(222, 222, 222));
        dt_tgl.setForeground(new java.awt.Color(222, 222, 222));

        tb_alamat.setBackground(new java.awt.Color(244, 244, 244));
        tb_alamat.setColumns(20);
        tb_alamat.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_alamat.setForeground(new java.awt.Color(58, 58, 58));
        tb_alamat.setRows(3);
        tb_alamat.setCaretColor(new java.awt.Color(58, 58, 58));
        jScrollPane1.setViewportView(tb_alamat);

        cb_jabatan.setBackground(new java.awt.Color(244, 244, 244));
        cb_jabatan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cb_jabatan.setForeground(new java.awt.Color(58, 58, 58));
        cb_jabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Kasir", "Marketing" }));
        cb_jabatan.setBorder(null);
        cb_jabatan.setOpaque(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(222, 222, 222));
        jLabel9.setText("Jabatan :");

        btn_deleteuser.setBackground(new java.awt.Color(222, 222, 222));
        btn_deleteuser.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        btn_deleteuser.setForeground(new java.awt.Color(58, 58, 58));
        btn_deleteuser.setText("Delete");
        btn_deleteuser.setBorder(null);
        btn_deleteuser.setContentAreaFilled(false);
        btn_deleteuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_deleteuser.setFocusPainted(false);
        btn_deleteuser.setOpaque(true);
        btn_deleteuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteuserActionPerformed(evt);
            }
        });

        btn_updateuser.setBackground(new java.awt.Color(222, 222, 222));
        btn_updateuser.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        btn_updateuser.setForeground(new java.awt.Color(58, 58, 58));
        btn_updateuser.setText(" Update");
        btn_updateuser.setBorder(null);
        btn_updateuser.setContentAreaFilled(false);
        btn_updateuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_updateuser.setFocusPainted(false);
        btn_updateuser.setOpaque(true);
        btn_updateuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateuserActionPerformed(evt);
            }
        });

        pl_titlebar.setBackground(new java.awt.Color(58, 58, 58));
        pl_titlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pl_titlebarMouseDragged(evt);
            }
        });
        pl_titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pl_titlebarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pl_titlebarMousePressed(evt);
            }
        });

        lbl_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_proyek/Images/times-solid.png"))); // NOI18N
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
        });

        lbl_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_proyek/Images/window-minimize-solid.png"))); // NOI18N
        lbl_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_minimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pl_titlebarLayout = new javax.swing.GroupLayout(pl_titlebar);
        pl_titlebar.setLayout(pl_titlebarLayout);
        pl_titlebarLayout.setHorizontalGroup(
            pl_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_titlebarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_minimize)
                .addGap(18, 18, 18)
                .addComponent(lbl_close)
                .addContainerGap())
        );
        pl_titlebarLayout.setVerticalGroup(
            pl_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pl_titlebarLayout.createSequentialGroup()
                .addGroup(pl_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pl_titlebarLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl_close))
                    .addComponent(lbl_minimize))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(222, 222, 222));
        jLabel2.setText("DETAIL ACCOUNT");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(222, 222, 222));
        jLabel10.setText("No Telepon :");

        tb_notelp.setBackground(new java.awt.Color(244, 244, 244));
        tb_notelp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_notelp.setForeground(new java.awt.Color(58, 58, 58));
        tb_notelp.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_notelp.setCaretColor(new java.awt.Color(58, 58, 58));
        tb_notelp.setMaximumSize(new java.awt.Dimension(6, 22));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(222, 222, 222));
        jLabel11.setText("Kota :");

        tb_kota.setBackground(new java.awt.Color(244, 244, 244));
        tb_kota.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_kota.setForeground(new java.awt.Color(58, 58, 58));
        tb_kota.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_kota.setCaretColor(new java.awt.Color(58, 58, 58));
        tb_kota.setMaximumSize(new java.awt.Dimension(6, 22));

        tb_email.setBackground(new java.awt.Color(244, 244, 244));
        tb_email.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_email.setForeground(new java.awt.Color(58, 58, 58));
        tb_email.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_email.setCaretColor(new java.awt.Color(58, 58, 58));
        tb_email.setMaximumSize(new java.awt.Dimension(6, 22));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(222, 222, 222));
        jLabel12.setText("Email :");

        btn_changepicture.setBackground(new java.awt.Color(222, 222, 222));
        btn_changepicture.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_changepicture.setForeground(new java.awt.Color(58, 58, 58));
        btn_changepicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_proyek/Images/wrench-solid.png"))); // NOI18N
        btn_changepicture.setText("Change Picture");
        btn_changepicture.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1));
        btn_changepicture.setContentAreaFilled(false);
        btn_changepicture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_changepicture.setFocusPainted(false);
        btn_changepicture.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_changepicture.setIconTextGap(10);
        btn_changepicture.setOpaque(true);
        btn_changepicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changepictureActionPerformed(evt);
            }
        });

        lbl_img.setBackground(new java.awt.Color(222, 222, 222));
        lbl_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_img.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_img.setIconTextGap(0);

        btn_removepicture.setBackground(new java.awt.Color(222, 222, 222));
        btn_removepicture.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_removepicture.setForeground(new java.awt.Color(58, 58, 58));
        btn_removepicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_proyek/Images/trash-solid.png"))); // NOI18N
        btn_removepicture.setText("Remove Picture");
        btn_removepicture.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1));
        btn_removepicture.setContentAreaFilled(false);
        btn_removepicture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_removepicture.setFocusPainted(false);
        btn_removepicture.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_removepicture.setIconTextGap(10);
        btn_removepicture.setOpaque(true);
        btn_removepicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removepictureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plLayout = new javax.swing.GroupLayout(pl);
        pl.setLayout(plLayout);
        plLayout.setHorizontalGroup(
            plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pl_titlebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(plLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(plLayout.createSequentialGroup()
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(plLayout.createSequentialGroup()
                                .addComponent(btn_updateuser, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_deleteuser, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_kode)
                            .addGroup(plLayout.createSequentialGroup()
                                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel11)
                                    .addComponent(tb_kota, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_img, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                    .addComponent(btn_changepicture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_removepicture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(dt_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(plLayout.createSequentialGroup()
                                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tb_notelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7)
                                            .addComponent(tb_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel10)
                                            .addComponent(tb_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel8)
                                            .addComponent(tb_password)
                                            .addComponent(jLabel9)
                                            .addComponent(cb_jabatan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12)
                                            .addComponent(tb_email, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(plLayout.createSequentialGroup()
                                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(rb_laki))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rb_perempuan)))))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        plLayout.setVerticalGroup(
            plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plLayout.createSequentialGroup()
                .addComponent(pl_titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(0, 0, 0)
                .addComponent(lbl_kode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plLayout.createSequentialGroup()
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tb_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(plLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb_notelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(plLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(plLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(plLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lbl_img, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_perempuan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb_laki, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_removepicture, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_changepicture, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(plLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_kota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(plLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dt_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_updateuser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deleteuser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_img.getAccessibleContext().setAccessibleName("lb_img");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing
    
    public boolean checkNama(String nama){
        String[] temp = nama.split(" ");
        if(temp.length >= 2){
            if(temp[0].length() < 2 || temp[1].length() < 2){
                return false;
            }
        }else{
            if(nama.length() < 4){
                return false;
            }
        }
        return true;
    }
    
     public boolean checkAngka(String t){
        try {
            int a = Integer.parseInt(t);
        } catch (Exception e) {
            return false;
        }
        return true;
    }
    
    
    public String checkValid(String gndr, String pw){
        String err = "";
        //Check Username password empty
        if(pw.equals("") || tb_username.getText().equals("")){
            err = "Username dan password tidak boleh kosong!";
        }
        //Check checked gender
        else if(gndr.equals("")){
            err = "Gender belum dipilih!";
        }
        else if(!checkNama(tb_nama.getText())){
            err = "Panjang nama invalid! Minimal tiap kata terdiri dari 2 huruf atau 4 huruf";
        }
        else if(tb_notelp.equals("")){
            err = "Nomor telepon tidak boleh kosong!";
        }else if (!checkAngka(tb_notelp.getText())){
            err = "Nomor telepon harus angka!";
        }else if(tb_email.getText().equals("")){
            err = "Email tidak boleh kosong!";
        }else if (!tb_email.getText().contains("@")){
            err = "Format email tidak valid!";
        }else if (tb_email.getText().substring(0,1).equals("@") || tb_email.getText().substring(tb_email.getText().length()).equals("@")){
            err = "Format email tidak valid!";
        }else{
            ArrayList<String[]> tmp = DB.query("SELECT count(*) FROM karyawan WHERE username = ?", new Object[] {tb_username.getText()});
            if(!tb_username.getText().equals(data_user[2])){
                if(!tmp.get(0)[0].equals("0")){
                    err = "Username sudah terpakai!";
                }
            }
        }
        return err;
    }
    
    private void btn_updateuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateuserActionPerformed
        // TODO add your handling code here:
        String gndr = rb_laki.isSelected() ? "L" : "P";
        String pw = String.valueOf(tb_password.getPassword());
        String err = checkValid(gndr, pw);
        if(err.equals("")){
            String dt = new SimpleDateFormat("yyyy-MM-dd").format(dt_tgl.getDate());
            String img_name = data_user[13];
            int output = 0;
            try {
                DB.autoCommit(false);
                if(f != null){
                    img_name = data_user[1] + "." + FilenameUtils.getExtension(f.getName());
                }else{
                    img_name = "NULL";
                }
                output = DB.update("UPDATE Karyawan SET username = ?, password = ?, nama = ?, nomor_telepon = ?, gender = ?, tanggal_lahir = ?, alamat = ?, kota = ?, fk_jabatan = ? , email = ?, images = ? WHERE id = ?", new Object[] {tb_username.getText(),pw,tb_nama.getText(),tb_notelp.getText() ,gndr,dt,tb_alamat.getText(),tb_kota.getText(),cb_jabatan.getSelectedIndex()+1,tb_email.getText(),img_name, data_user[0]});
                if(f != null){
                    File f_copy = new File(System.getProperty("user.dir")+"/Images/User/"+img_name);
                    FileUtils.copyFile(f, f_copy);
                }
                DB.f_commit();
            } catch (Exception e) {
                DB.f_rollback();
                output = 0;
            }
            if(output != 0){
                frm_acc.loadDgv();
                frm_acc.search();
                frm_acc.setIdx(-1);
                JOptionPane.showMessageDialog(null, "Sukses ubah data","Sukses",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Gagal ubah data!","Error",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, err,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_updateuserActionPerformed

    private void btn_deleteuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteuserActionPerformed
        // TODO add your handling code here:
        if(lbl_kode.getText().equalsIgnoreCase(User.getUser_login().getKode())){
            JOptionPane.showMessageDialog(null, "Tidak bisa menghapus user yang sedang login!","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            if(JOptionPane.showConfirmDialog(null, "Yakin hapus user "+data_user[2]+" ?","Hapus User",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                int output = DB.delete("UPDATE karyawan SET STATUS = 0 WHERE id = ?",new Object[] {data_user[0]});
                if(output <= 0){
                    JOptionPane.showMessageDialog(null, "Error saat menghapus!","Error",JOptionPane.ERROR_MESSAGE);
                }else{
                    frm_acc.loadDgv();
                    frm_acc.search();
                    frm_acc.setIdx(-1);
                    JOptionPane.showMessageDialog(null, "Sukses delete user","Sukses",JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_btn_deleteuserActionPerformed

    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lbl_closeMouseClicked
    
    int state_mode = -1; //-1 not full, 1 full screen
    private int x,y;
    
    private void lbl_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizeMouseClicked
        // TODO add your handling code here:
        setState(this.ICONIFIED);
    }//GEN-LAST:event_lbl_minimizeMouseClicked
    private void pl_titlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pl_titlebarMouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);

    }//GEN-LAST:event_pl_titlebarMouseDragged

    private void pl_titlebarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pl_titlebarMouseClicked
    }//GEN-LAST:event_pl_titlebarMouseClicked

    private void pl_titlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pl_titlebarMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pl_titlebarMousePressed
    
    BufferedImage bi;
    
    // 0 --> File select,
    // 1 --> DB,
    // -1 --> angka random. supaya keluar image not found
    public void loadImage(String fileName, int mode){
        InputStream is;
        Image img;
        ImageIcon img_icon;
        try {
            if(!fileName.equalsIgnoreCase("null") && !fileName.equals("")){
                if(mode == 0){
                    is = new FileInputStream(fileName);
                }else{
                    is = new FileInputStream(System.getProperty("user.dir")+"/Images/User/"+fileName);
                }
            }else{
                is = Form_Login.class.getResourceAsStream("Images/no_img.png");
            }
            bi = ImageIO.read(is);
            img = bi.getScaledInstance(lbl_img.getWidth(), -1, Image.SCALE_SMOOTH);
            img_icon = new ImageIcon(img);
            lbl_img.setIcon(img_icon);
        }catch (FileNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Image not found","Error",JOptionPane.ERROR_MESSAGE);
            f = null;
            loadImage("null",0);
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Bad file format","Error",JOptionPane.ERROR_MESSAGE);
            f = null;
            loadImage("null",0);
        }
    }
    
    
    File f;
    private void btn_changepictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changepictureActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images", "jpg", "jpeg", "png", "bmp");
        fc.setFileFilter(filter);
        int result = fc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            f = fc.getSelectedFile();
            loadImage(f.getPath(),0);
        }
    }//GEN-LAST:event_btn_changepictureActionPerformed

    private void btn_removepictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removepictureActionPerformed
        // TODO add your handling code here:
        f = null;
        loadImage("", -1);
    }//GEN-LAST:event_btn_removepictureActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailAccount_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailAccount_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailAccount_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailAccount_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailAccount_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_changepicture;
    private javax.swing.JButton btn_deleteuser;
    private javax.swing.JButton btn_removepicture;
    private javax.swing.JButton btn_updateuser;
    private javax.swing.JComboBox<String> cb_jabatan;
    private com.toedter.calendar.JDateChooser dt_tgl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JLabel lbl_kode;
    private javax.swing.JLabel lbl_minimize;
    private javax.swing.JPanel pl;
    private javax.swing.JPanel pl_titlebar;
    private javax.swing.JRadioButton rb_laki;
    private javax.swing.JRadioButton rb_perempuan;
    private javax.swing.JTextArea tb_alamat;
    private javax.swing.JTextField tb_email;
    private javax.swing.JTextField tb_kota;
    private javax.swing.JTextField tb_nama;
    private javax.swing.JTextField tb_notelp;
    private javax.swing.JPasswordField tb_password;
    private javax.swing.JTextField tb_username;
    // End of variables declaration//GEN-END:variables
}
