/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package pbo_proyek;

import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author chris
 */
public class InsertAccount_Form extends javax.swing.JFrame {
    
    /**
     * Creates new form InsertAccount_Form
     */
    ButtonGroup btng1;
    public InsertAccount_Form() {
        initComponents();
        btng1 = new ButtonGroup();
        btng1.add(rb_laki);
        btng1.add(rb_perempuan);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        pl_titlebar = new javax.swing.JPanel();
        lbl_close = new javax.swing.JLabel();
        lbl_minimize = new javax.swing.JLabel();
        pl = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tb_nama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cb_jabatan = new javax.swing.JComboBox<>();
        tb_password = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        tb_username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rb_laki = new javax.swing.JRadioButton();
        rb_perempuan = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        dt_tgl = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_alamat = new javax.swing.JTextArea();
        btn_tambah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pl_foto = new javax.swing.JPanel();
        tb_kota = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tb_email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tb_notelp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btn_changepicture = new javax.swing.JButton();

        jLabel8.setForeground(new java.awt.Color(222, 222, 222));
        jLabel8.setText("Password :");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setMaximumSize(new java.awt.Dimension(493, 491));
        setMinimumSize(new java.awt.Dimension(493, 491));
        setUndecorated(true);

        pl_titlebar.setBackground(new java.awt.Color(58, 58, 58));
        pl_titlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pl_titlebarMouseDragged(evt);
            }
        });
        pl_titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pl_titlebarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pl_titlebarMousePressed(evt);
            }
        });

        lbl_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_proyek/Images/times-solid.png"))); // NOI18N
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
        });

        lbl_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_proyek/Images/window-minimize-solid.png"))); // NOI18N
        lbl_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_minimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pl_titlebarLayout = new javax.swing.GroupLayout(pl_titlebar);
        pl_titlebar.setLayout(pl_titlebarLayout);
        pl_titlebarLayout.setHorizontalGroup(
            pl_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_titlebarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_minimize)
                .addGap(18, 18, 18)
                .addComponent(lbl_close)
                .addContainerGap())
        );
        pl_titlebarLayout.setVerticalGroup(
            pl_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pl_titlebarLayout.createSequentialGroup()
                .addGroup(pl_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pl_titlebarLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl_close))
                    .addComponent(lbl_minimize))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        pl.setBackground(new java.awt.Color(58, 58, 58));

        jLabel4.setForeground(new java.awt.Color(222, 222, 222));
        jLabel4.setText("Nama :");

        tb_nama.setBackground(new java.awt.Color(244, 244, 244));
        tb_nama.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_nama.setForeground(new java.awt.Color(58, 58, 58));
        tb_nama.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_nama.setCaretColor(new java.awt.Color(58, 58, 58));

        jLabel9.setForeground(new java.awt.Color(222, 222, 222));
        jLabel9.setText("Jabatan :");

        cb_jabatan.setBackground(new java.awt.Color(244, 244, 244));
        cb_jabatan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cb_jabatan.setForeground(new java.awt.Color(58, 58, 58));
        cb_jabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Kasir", "Marketing" }));
        cb_jabatan.setBorder(null);
        cb_jabatan.setOpaque(false);

        tb_password.setBackground(new java.awt.Color(244, 244, 244));
        tb_password.setForeground(new java.awt.Color(58, 58, 58));

        jLabel10.setForeground(new java.awt.Color(222, 222, 222));
        jLabel10.setText("Password :");

        tb_username.setBackground(new java.awt.Color(244, 244, 244));
        tb_username.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_username.setForeground(new java.awt.Color(58, 58, 58));
        tb_username.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_username.setCaretColor(new java.awt.Color(58, 58, 58));

        jLabel7.setForeground(new java.awt.Color(222, 222, 222));
        jLabel7.setText("Username :");

        jLabel3.setForeground(new java.awt.Color(222, 222, 222));
        jLabel3.setText("Jenis Kelamin :");

        rb_laki.setBackground(new java.awt.Color(58, 58, 58));
        rb_laki.setForeground(new java.awt.Color(222, 222, 222));
        rb_laki.setText("Laki - Laki");

        rb_perempuan.setBackground(new java.awt.Color(58, 58, 58));
        rb_perempuan.setForeground(new java.awt.Color(222, 222, 222));
        rb_perempuan.setText("Perempuan");

        jLabel6.setForeground(new java.awt.Color(222, 222, 222));
        jLabel6.setText("Tanggal Lahir :");

        dt_tgl.setBackground(new java.awt.Color(222, 222, 222));
        dt_tgl.setForeground(new java.awt.Color(222, 222, 222));

        jLabel5.setForeground(new java.awt.Color(222, 222, 222));
        jLabel5.setText("Alamat :");

        tb_alamat.setBackground(new java.awt.Color(244, 244, 244));
        tb_alamat.setColumns(20);
        tb_alamat.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_alamat.setForeground(new java.awt.Color(58, 58, 58));
        tb_alamat.setRows(3);
        tb_alamat.setCaretColor(new java.awt.Color(58, 58, 58));
        jScrollPane1.setViewportView(tb_alamat);

        btn_tambah.setBackground(new java.awt.Color(222, 222, 222));
        btn_tambah.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(58, 58, 58));
        btn_tambah.setText("Tambah");
        btn_tambah.setBorder(null);
        btn_tambah.setContentAreaFilled(false);
        btn_tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tambah.setFocusPainted(false);
        btn_tambah.setOpaque(true);
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(222, 222, 222));
        jLabel2.setText("INSERT ACCOUNT");

        pl_foto.setBackground(new java.awt.Color(222, 222, 222));

        javax.swing.GroupLayout pl_fotoLayout = new javax.swing.GroupLayout(pl_foto);
        pl_foto.setLayout(pl_fotoLayout);
        pl_fotoLayout.setHorizontalGroup(
            pl_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        pl_fotoLayout.setVerticalGroup(
            pl_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );

        tb_kota.setBackground(new java.awt.Color(244, 244, 244));
        tb_kota.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_kota.setForeground(new java.awt.Color(58, 58, 58));
        tb_kota.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_kota.setCaretColor(new java.awt.Color(58, 58, 58));

        jLabel11.setForeground(new java.awt.Color(222, 222, 222));
        jLabel11.setText("Kota :");

        tb_email.setBackground(new java.awt.Color(244, 244, 244));
        tb_email.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_email.setForeground(new java.awt.Color(58, 58, 58));
        tb_email.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_email.setCaretColor(new java.awt.Color(58, 58, 58));

        jLabel12.setForeground(new java.awt.Color(222, 222, 222));
        jLabel12.setText("Email :");

        tb_notelp.setBackground(new java.awt.Color(244, 244, 244));
        tb_notelp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_notelp.setForeground(new java.awt.Color(58, 58, 58));
        tb_notelp.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_notelp.setCaretColor(new java.awt.Color(58, 58, 58));

        jLabel13.setForeground(new java.awt.Color(222, 222, 222));
        jLabel13.setText("No Telepon :");

        btn_changepicture.setBackground(new java.awt.Color(222, 222, 222));
        btn_changepicture.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_changepicture.setForeground(new java.awt.Color(58, 58, 58));
        btn_changepicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_proyek/Images/wrench-solid.png"))); // NOI18N
        btn_changepicture.setText("Change Picture");
        btn_changepicture.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1));
        btn_changepicture.setContentAreaFilled(false);
        btn_changepicture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_changepicture.setFocusPainted(false);
        btn_changepicture.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_changepicture.setIconTextGap(10);
        btn_changepicture.setOpaque(true);

        javax.swing.GroupLayout plLayout = new javax.swing.GroupLayout(pl);
        pl.setLayout(plLayout);
        plLayout.setHorizontalGroup(
            plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plLayout.createSequentialGroup()
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_changepicture, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(jLabel11)
                            .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tb_kota))
                        .addGap(18, 18, 18)
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(plLayout.createSequentialGroup()
                                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dt_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(plLayout.createSequentialGroup()
                                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(plLayout.createSequentialGroup()
                                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(tb_username, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel10)
                                            .addComponent(tb_password, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addGroup(plLayout.createSequentialGroup()
                                            .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel4)
                                                .addComponent(tb_nama, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                                .addComponent(jLabel13)
                                                .addComponent(tb_notelp))
                                            .addGap(18, 18, 18)
                                            .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel9)
                                                .addComponent(cb_jabatan, 0, 135, Short.MAX_VALUE)
                                                .addComponent(jLabel12)
                                                .addComponent(tb_email))))
                                    .addGroup(plLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(plLayout.createSequentialGroup()
                                                .addComponent(rb_laki)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rb_perempuan)))))
                                .addGap(0, 13, Short.MAX_VALUE))))
                    .addGroup(plLayout.createSequentialGroup()
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        plLayout.setVerticalGroup(
            plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(plLayout.createSequentialGroup()
                        .addComponent(pl_foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(btn_changepicture, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(plLayout.createSequentialGroup()
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tb_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(plLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb_notelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(plLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(plLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(plLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rb_perempuan, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rb_laki, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(7, 7, 7)
                        .addComponent(dt_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(plLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_kota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pl_titlebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pl_titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    int state_mode = -1; //-1 not full, 1 full screen
    private int x,y;
    
    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lbl_closeMouseClicked

    private void lbl_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizeMouseClicked
        // TODO add your handling code here:
        setState(this.ICONIFIED);
    }//GEN-LAST:event_lbl_minimizeMouseClicked

    private void pl_titlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pl_titlebarMouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_pl_titlebarMouseDragged

    private void pl_titlebarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pl_titlebarMouseClicked

    }//GEN-LAST:event_pl_titlebarMouseClicked
    
    private Form_Account frm_acc;
    
    public Form_Account getFrm_acc() {
        return frm_acc;
    }
    
    public void setFrm_acc(Form_Account frm_acc) {
        this.frm_acc = frm_acc;
    }
    
    
    private void pl_titlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pl_titlebarMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pl_titlebarMousePressed
    
    public String checkValid(String gndr, String pw){
        String err = "";
        //Check Username password empty
        if(pw.equals("") || tb_username.getText().equals("")){
            err = "Username dan password tidak boleh kosong!";
        }
        //Check checked gender
        else if(gndr.equals("")){
            err = "Gender belum dipilih!";
        }
        else if(!checkNama(tb_nama.getText())){
            err = "Panjang nama invalid! Minimal tiap kata terdiri dari 2 huruf atau 4 huruf";
        }
        else if(tb_notelp.equals("")){
            err = "Nomor telepon tidak boleh kosong!";
        }else if(tb_email.getText().equals("")){
            err = "Email tidak boleh kosong!";
        }else{
            ArrayList<String[]> tmp = DB.query("SELECT count(*) FROM karyawan WHERE username = ?", new Object[] {tb_username.getText()});
            if(!tmp.get(0)[0].equals("0")){
                err = "Username sudah terpakai!";
            }
        }
        return err;
    }
    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        String gndr = "";
        if(rb_laki.isSelected()){
            gndr = "L";
        }else if(rb_perempuan.isSelected()){
            gndr = "P";
        }
        String pw = String.valueOf(tb_password.getPassword());
        String err = checkValid(gndr, pw);
        if(err.equals("")){
            String kode = generateKode(tb_nama.getText());
            boolean valid = DB.insert("INSERT INTO karyawan(kode,username,password,nama,nomor_telepon,gender,tanggal_lahir,kota,alamat,status,fk_jabatan,email) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", new Object[] {kode,tb_username.getText(),pw,tb_nama.getText(),tb_notelp.getText(),gndr,dt_tgl.getDate(),tb_kota.getText(),tb_alamat.getText(),1,cb_jabatan.getSelectedIndex()+1,tb_email.getText()});
            if(valid){
                JOptionPane.showMessageDialog(null, "Insert Sukses!","Sukses",JOptionPane.INFORMATION_MESSAGE);
                frm_acc.loadDgv();
                frm_acc.search();
                frm_acc.setIdx(-1);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Insert gagal!","Error",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, err,"Error",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_tambahActionPerformed
    
    public boolean checkNama(String nama){
        String[] temp = nama.split(" ");
        if(temp.length >= 2){
            if(temp[0].length() < 2 || temp[1].length() < 2){
                return false;
            }
        }else{
            if(nama.length() < 4){
                return false;
            }
        }
        return true;
    }
    
    public String generateKode(String nama){
        String[] temp = nama.split(" ");
        String kode_final = "";
        if(temp.length >= 2){
            kode_final += temp[0].substring(0, 2);
            kode_final += temp[1].substring(0, 2);
        }else{
            kode_final += nama.substring(0, 4);
        }
        kode_final = kode_final.toUpperCase();
        ArrayList<String[]> res = DB.query("select LPAD(count(*)+1,4,'0') from karyawan where kode like '%"+kode_final+"%'");
        kode_final += res.get(0)[0];
        return kode_final;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertAccount_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertAccount_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertAccount_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertAccount_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertAccount_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_changepicture;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox<String> cb_jabatan;
    private com.toedter.calendar.JDateChooser dt_tgl;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_minimize;
    private javax.swing.JPanel pl;
    private javax.swing.JPanel pl_foto;
    private javax.swing.JPanel pl_titlebar;
    private javax.swing.JRadioButton rb_laki;
    private javax.swing.JRadioButton rb_perempuan;
    private javax.swing.JTextArea tb_alamat;
    private javax.swing.JTextField tb_email;
    private javax.swing.JTextField tb_kota;
    private javax.swing.JTextField tb_nama;
    private javax.swing.JTextField tb_notelp;
    private javax.swing.JPasswordField tb_password;
    private javax.swing.JTextField tb_username;
    // End of variables declaration//GEN-END:variables
}
