/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbo_proyek;

/**
 *
 * @author Kevin
 */
public class InsertBarang_Form extends javax.swing.JFrame {

    /**
     * Creates new form InsertBarang_Form
     */
    public InsertBarang_Form() {
        initComponents();
    }
    private Form_Stock frm_acc;
    
    public Form_Stock getFrm_acc() {
        return frm_acc;
    }
    
    public void setFrm_acc(Form_Stock frm_acc) {
        this.frm_acc = frm_acc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pl_titlebar = new javax.swing.JPanel();
        lbl_close = new javax.swing.JLabel();
        lbl_minimize = new javax.swing.JLabel();
        pl = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tb_nama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cb_jabatan = new javax.swing.JComboBox<>();
        tb_password = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        tb_username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pl_titlebar.setBackground(new java.awt.Color(58, 58, 58));
        pl_titlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pl_titlebarMouseDragged(evt);
            }
        });
        pl_titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pl_titlebarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pl_titlebarMousePressed(evt);
            }
        });

        lbl_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_proyek/Images/times-solid.png"))); // NOI18N
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
        });

        lbl_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_proyek/Images/window-minimize-solid.png"))); // NOI18N
        lbl_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_minimizeMouseClicked(evt);
            }
        });

        pl.setBackground(new java.awt.Color(58, 58, 58));

        jLabel4.setForeground(new java.awt.Color(222, 222, 222));
        jLabel4.setText("Nama Barang:");

        tb_nama.setBackground(new java.awt.Color(244, 244, 244));
        tb_nama.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_nama.setForeground(new java.awt.Color(58, 58, 58));
        tb_nama.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_nama.setCaretColor(new java.awt.Color(58, 58, 58));

        jLabel9.setForeground(new java.awt.Color(222, 222, 222));
        jLabel9.setText("Jenis Barang:");

        cb_jabatan.setBackground(new java.awt.Color(244, 244, 244));
        cb_jabatan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cb_jabatan.setForeground(new java.awt.Color(58, 58, 58));
        cb_jabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Kasir", "Marketing" }));
        cb_jabatan.setBorder(null);
        cb_jabatan.setOpaque(false);

        tb_password.setBackground(new java.awt.Color(244, 244, 244));
        tb_password.setForeground(new java.awt.Color(58, 58, 58));

        jLabel10.setForeground(new java.awt.Color(222, 222, 222));
        jLabel10.setText("Stok Barang:");

        tb_username.setBackground(new java.awt.Color(244, 244, 244));
        tb_username.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_username.setForeground(new java.awt.Color(58, 58, 58));
        tb_username.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_username.setCaretColor(new java.awt.Color(58, 58, 58));

        jLabel7.setForeground(new java.awt.Color(222, 222, 222));
        jLabel7.setText("Harga Barang:");

        btn_tambah.setBackground(new java.awt.Color(222, 222, 222));
        btn_tambah.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(58, 58, 58));
        btn_tambah.setText("Tambah");
        btn_tambah.setBorder(null);
        btn_tambah.setContentAreaFilled(false);
        btn_tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tambah.setFocusPainted(false);
        btn_tambah.setOpaque(true);
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plLayout = new javax.swing.GroupLayout(pl);
        pl.setLayout(plLayout);
        plLayout.setHorizontalGroup(
            plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(plLayout.createSequentialGroup()
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(tb_nama)
                            .addComponent(tb_username, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(cb_jabatan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9)
                            .addComponent(tb_password, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        plLayout.setVerticalGroup(
            plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plLayout.createSequentialGroup()
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(plLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pl_titlebarLayout = new javax.swing.GroupLayout(pl_titlebar);
        pl_titlebar.setLayout(pl_titlebarLayout);
        pl_titlebarLayout.setHorizontalGroup(
            pl_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_titlebarLayout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addComponent(lbl_minimize)
                .addGap(18, 18, 18)
                .addComponent(lbl_close)
                .addContainerGap())
            .addGroup(pl_titlebarLayout.createSequentialGroup()
                .addComponent(pl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pl_titlebarLayout.setVerticalGroup(
            pl_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pl_titlebarLayout.createSequentialGroup()
                .addGroup(pl_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pl_titlebarLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl_close))
                    .addComponent(lbl_minimize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pl_titlebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pl_titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:

        if(!checkNama(tb_nama.getText())){
            JOptionPane.showMessageDialog(null, "Panjang minimal nama invalid!","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            String pw = String.valueOf(tb_password.getPassword());
            if(pw.equalsIgnoreCase("") || tb_username.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Username dan password tidak boleh kosong!","Error",JOptionPane.ERROR_MESSAGE);
            }else{
                String gndr = "";
                if(rb_laki.isSelected()){
                    gndr = "L";
                }else if(rb_perempuan.isSelected()){
                    gndr = "P";
                }
                if(gndr.equalsIgnoreCase("")){
                    JOptionPane.showMessageDialog(null, "Gender belum dipilih!","Error",JOptionPane.ERROR_MESSAGE);
                }else{
                    String kode = generateKode(tb_nama.getText());
                    System.out.println(kode);
                    boolean valid = DB.insert("INSERT INTO karyawan(kode,username,password,nama,gender,tanggal_lahir,alamat,status,fk_jabatan) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)", new Object[] {kode,tb_username.getText(),pw,tb_nama.getText(),gndr,dt_tgl.getDate(),tb_alamat.getText(),1,cb_jabatan.getSelectedIndex()+1});
                    if(valid){
                        JOptionPane.showMessageDialog(null, "Insert Sukses!","Sukses",JOptionPane.INFORMATION_MESSAGE);
                        frm_acc.loadDgv();
                        frm_acc.search();
                        frm_acc.setIdx(-1);
                        this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(null, "Insert gagal!","Error",JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lbl_closeMouseClicked

    private void lbl_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizeMouseClicked
        // TODO add your handling code here:
        setState(this.ICONIFIED);
    }//GEN-LAST:event_lbl_minimizeMouseClicked

    private void pl_titlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pl_titlebarMouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_pl_titlebarMouseDragged

    private void pl_titlebarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pl_titlebarMouseClicked

    }//GEN-LAST:event_pl_titlebarMouseClicked

    private void pl_titlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pl_titlebarMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pl_titlebarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertBarang_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertBarang_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertBarang_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertBarang_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertBarang_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox<String> cb_jabatan;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_minimize;
    private javax.swing.JPanel pl;
    private javax.swing.JPanel pl_titlebar;
    private javax.swing.JTextField tb_nama;
    private javax.swing.JPasswordField tb_password;
    private javax.swing.JTextField tb_username;
    // End of variables declaration//GEN-END:variables
}
