/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbo_proyek;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class InsertBarang_Form extends javax.swing.JFrame {

    int state_mode = -1; //-1 not full, 1 full screen
    private int x,y;
    ArrayList<String[]> listJenis;
    /**
     * Creates new form InsertBarang_Form
     */
    public InsertBarang_Form() {
        initComponents();
        listJenis = DB.query("SELECT * FROM JENIS_BARANG");
        
        for (String[] s :listJenis) {
            cb_jenis.addItem(s[1]);
        }
        
    }
    private Form_Stock frm_acc;
    
    public Form_Stock getFrm_acc() {
        return frm_acc;
    }
    
    public void setFrm_acc(Form_Stock frm_acc) {
        this.frm_acc = frm_acc;
    }
    public boolean checkNama(String nama){
        String[] temp = nama.split(" ");
        if(temp.length >= 2){
            if(temp[0].length() < 2 || temp[1].length() < 2){
                return false;
            }
        }else{
            if(nama.length() < 4){
                return false;
            }
        }
        return true;
    }
    public String generateKode(String nama){
        String[] temp = nama.split(" ");
        String kode_final = "";
        if(temp.length >= 2){
            kode_final += temp[0].substring(0, 2);
            kode_final += temp[1].substring(0, 2);
        }else{
            kode_final += nama.substring(0, 4);
        }
        kode_final = kode_final.toUpperCase();
        ArrayList<String[]> res = DB.query("select LPAD(count(*)+1,4,'0') from barang where kode like '%"+kode_final+"%'");
        kode_final += res.get(0)[0];
        return kode_final;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pl_titlebar = new javax.swing.JPanel();
        lbl_close = new javax.swing.JLabel();
        lbl_minimize = new javax.swing.JLabel();
        pl = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_jenis = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        tb_harga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JButton();
        tb_stok = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pl_foto = new javax.swing.JPanel();
        btn_changepicture = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_nama = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pl_titlebar.setBackground(new java.awt.Color(58, 58, 58));
        pl_titlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pl_titlebarMouseDragged(evt);
            }
        });
        pl_titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pl_titlebarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pl_titlebarMousePressed(evt);
            }
        });

        lbl_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_proyek/Images/times-solid.png"))); // NOI18N
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
        });

        lbl_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_proyek/Images/window-minimize-solid.png"))); // NOI18N
        lbl_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_minimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pl_titlebarLayout = new javax.swing.GroupLayout(pl_titlebar);
        pl_titlebar.setLayout(pl_titlebarLayout);
        pl_titlebarLayout.setHorizontalGroup(
            pl_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pl_titlebarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_minimize)
                .addGap(18, 18, 18)
                .addComponent(lbl_close)
                .addContainerGap())
        );
        pl_titlebarLayout.setVerticalGroup(
            pl_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pl_titlebarLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(lbl_close))
            .addComponent(lbl_minimize)
        );

        pl.setBackground(new java.awt.Color(58, 58, 58));

        jLabel4.setForeground(new java.awt.Color(222, 222, 222));
        jLabel4.setText("Nama Barang:");

        jLabel9.setForeground(new java.awt.Color(222, 222, 222));
        jLabel9.setText("Jenis Barang:");

        cb_jenis.setBackground(new java.awt.Color(244, 244, 244));
        cb_jenis.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cb_jenis.setForeground(new java.awt.Color(58, 58, 58));
        cb_jenis.setBorder(null);
        cb_jenis.setOpaque(false);

        jLabel10.setForeground(new java.awt.Color(222, 222, 222));
        jLabel10.setText("Stok Barang:");

        tb_harga.setBackground(new java.awt.Color(244, 244, 244));
        tb_harga.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_harga.setForeground(new java.awt.Color(58, 58, 58));
        tb_harga.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_harga.setCaretColor(new java.awt.Color(58, 58, 58));

        jLabel7.setForeground(new java.awt.Color(222, 222, 222));
        jLabel7.setText("Harga Barang:");

        btn_tambah.setBackground(new java.awt.Color(222, 222, 222));
        btn_tambah.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(58, 58, 58));
        btn_tambah.setText("Tambah");
        btn_tambah.setBorder(null);
        btn_tambah.setContentAreaFilled(false);
        btn_tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tambah.setFocusPainted(false);
        btn_tambah.setOpaque(true);
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        tb_stok.setBackground(new java.awt.Color(244, 244, 244));
        tb_stok.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_stok.setForeground(new java.awt.Color(58, 58, 58));
        tb_stok.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tb_stok.setCaretColor(new java.awt.Color(58, 58, 58));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(222, 222, 222));
        jLabel2.setText("INSERT BARANG");

        pl_foto.setBackground(new java.awt.Color(222, 222, 222));

        javax.swing.GroupLayout pl_fotoLayout = new javax.swing.GroupLayout(pl_foto);
        pl_foto.setLayout(pl_fotoLayout);
        pl_fotoLayout.setHorizontalGroup(
            pl_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pl_fotoLayout.setVerticalGroup(
            pl_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );

        btn_changepicture.setBackground(new java.awt.Color(222, 222, 222));
        btn_changepicture.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_changepicture.setForeground(new java.awt.Color(58, 58, 58));
        btn_changepicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo_proyek/Images/wrench-solid.png"))); // NOI18N
        btn_changepicture.setText("Change Picture");
        btn_changepicture.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1));
        btn_changepicture.setContentAreaFilled(false);
        btn_changepicture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_changepicture.setFocusPainted(false);
        btn_changepicture.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_changepicture.setIconTextGap(10);
        btn_changepicture.setOpaque(true);

        tb_nama.setBackground(new java.awt.Color(244, 244, 244));
        tb_nama.setColumns(20);
        tb_nama.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tb_nama.setForeground(new java.awt.Color(58, 58, 58));
        tb_nama.setRows(5);
        tb_nama.setCaretColor(new java.awt.Color(58, 58, 58));
        jScrollPane1.setViewportView(tb_nama);

        javax.swing.GroupLayout plLayout = new javax.swing.GroupLayout(pl);
        pl.setLayout(plLayout);
        plLayout.setHorizontalGroup(
            plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pl_foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_changepicture, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(plLayout.createSequentialGroup()
                        .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(cb_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(tb_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tb_stok, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(plLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(72, 72, 72)))
                            .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        plLayout.setVerticalGroup(
            plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(plLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pl_foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(plLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_changepicture, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(plLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tb_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pl_titlebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pl_titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pl, javax.swing.GroupLayout.PREFERRED_SIZE, 375, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        if(!checkNama(tb_nama.getText())){
            JOptionPane.showMessageDialog(null, "Panjang minimal nama invalid!","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            if (tb_stok.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Stok Barang tidak boleh kosong!","Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
              int stck = Integer.parseInt(tb_stok.getText());
              if (stck < 0){
                  JOptionPane.showMessageDialog(null, "Stok Barang tidak boleh kurang dari 0!","Error",JOptionPane.ERROR_MESSAGE);
              }
              else{
                  if(tb_nama.getText().equals("")){
                      JOptionPane.showMessageDialog(null, "Nama Barang tidak boleh kosong!","Error",JOptionPane.ERROR_MESSAGE);
                  }
                  else{
                      if(tb_harga.getText().equals("")){
                          JOptionPane.showMessageDialog(null, "harga Barang tidak boleh kosong!","Error",JOptionPane.ERROR_MESSAGE);
                      }
                      else{
                          int hrg = Integer.parseInt(tb_harga.getText());
                          if (hrg < 1){
                              JOptionPane.showMessageDialog(null, "Harga Barang tidak boleh kurang dari 1!","Error",JOptionPane.ERROR_MESSAGE);
                          }
                          else{
                              if(cb_jenis.getSelectedItem().toString().equals("")){
                                  JOptionPane.showMessageDialog(null, "Jenis Barang tidak boleh kosong!","Error",JOptionPane.ERROR_MESSAGE);
                              }
                              else{
                                  String kode = generateKode(tb_nama.getText());
                                  System.out.println(kode);
                                  boolean valid = DB.insert("INSERT INTO barang(kode,nama,stok,harga,status,fk_jenis_barang) VALUES(?, ?, ?, ?, ?, ?)", new Object[] {kode,tb_nama.getText(),stck,hrg,1,cb_jenis.getSelectedIndex()+1});
                                    if(valid){
                                        JOptionPane.showMessageDialog(null, "Insert Sukses!","Sukses",JOptionPane.INFORMATION_MESSAGE);
                                        frm_acc.loadDgv();
                                        frm_acc.search();
                                        frm_acc.setIdx(-1);
                                        this.dispose();
                                    }else{
                                        JOptionPane.showMessageDialog(null, "Insert gagal!","Error",JOptionPane.ERROR_MESSAGE);
                                    }
                              }
                          }
                      }
                  }
              }
            }
            
        }
        
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lbl_closeMouseClicked

    private void lbl_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizeMouseClicked
        // TODO add your handling code here:
        setState(this.ICONIFIED);
    }//GEN-LAST:event_lbl_minimizeMouseClicked

    private void pl_titlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pl_titlebarMouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_pl_titlebarMouseDragged

    private void pl_titlebarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pl_titlebarMouseClicked

    }//GEN-LAST:event_pl_titlebarMouseClicked

    private void pl_titlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pl_titlebarMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pl_titlebarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertBarang_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertBarang_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertBarang_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertBarang_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertBarang_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_changepicture;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox<String> cb_jenis;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_minimize;
    private javax.swing.JPanel pl;
    private javax.swing.JPanel pl_foto;
    private javax.swing.JPanel pl_titlebar;
    private javax.swing.JTextField tb_harga;
    private javax.swing.JTextArea tb_nama;
    private javax.swing.JTextField tb_stok;
    // End of variables declaration//GEN-END:variables
}
